
name: SBOM upload

on: 
  workflow_dispatch:

jobs:
  SBOM-upload:

    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: write
      
    steps:
    - uses: actions/checkout@v5
    # - name: Generate SBOM
      # run: | 
        # curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        # chmod +x $RUNNER_TEMP/sbom-tool
        # $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn ${{ github.repository }} -pv 1.0.0 -ps OwnerName -nsb https://sbom.mycompany.com -V Verbose
    - uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: ./project.spdx.yml
    - name: SBOM upload 
      uses: advanced-security/spdx-dependency-submission-action@v0.1.1
      with:
        filePath: "./project.spdx.yml"